version "4.10"

#include "zscript/HEV Armor/hevArmor.zs"
#include "zscript/PD-42/pd42.zs"
#include "zscript/Barracuda/barracuda.zs"
#include "zscript/Flamenwerfer 77/flamenwerfer77.zs"
#include "zscript/Frontiersman/frontiersman.zs"
#include "zscript/Hammerhead/hammerhead.zs"
#include "zscript/Scorpion/scorpion.zs"
#include "zscript/Six12/six12.zs"
#include "zscript/Viper/viper.zs"
#include "zscript/Wyvern/wyvern.zs"
