version "4.10"

#include "zscript/icarus/SpawnHandler.zs"

#include "zscript/icarus/weapons/Barracuda/barracuda.zs"
#include "zscript/icarus/weapons/Bitch/bitch.zs"
#include "zscript/icarus/weapons/Fenris/fenris.zs"
#include "zscript/icarus/weapons/Flamenwerfer 77/flamenwerfer77.zs"
#include "zscript/icarus/weapons/Frontiersman/frontiersman.zs"
#include "zscript/icarus/weapons/GFB-9/gfb9.zs"
#include "zscript/icarus/weapons/Hammerhead/hammerhead.zs"
#include "zscript/icarus/weapons/HEV Armor/hevArmor.zs"
#include "zscript/icarus/weapons/NCT/nct.zs"
#include "zscript/icarus/weapons/Nyx/nyx.zs"
#include "zscript/icarus/weapons/PD-42/pd42.zs"
#include "zscript/icarus/weapons/Scorpion/scorpion.zs"
#include "zscript/icarus/weapons/Six12/six12.zs"
#include "zscript/icarus/weapons/UMP/ump.zs"
#include "zscript/icarus/weapons/USP/usp.zs"
#include "zscript/icarus/weapons/Viper/viper.zs"
#include "zscript/icarus/weapons/Wyvern/wyvern.zs"